resolver: lts-8.21

packages:
- '.'
extra-deps: [time-units-1.0.0, saltine-0.1.0.0]

flags: {}

extra-package-dbs: []

nix:
  pure: true
  enable: false 
  packages: [ gcc, ncurses, zlib, libsodium, pkgconfig, postgresql ]